//
// Created by yareach on 25. 8. 18..
//

#ifndef LIVE_NOTIFICATOR_DEVICE_MESSAGE_TYPE_H
#define LIVE_NOTIFICATOR_DEVICE_MESSAGE_TYPE_H

enum MessageType {
    UPDATED, REFRESHED, INFO_CHANGED, STATE_CHANGED, IMAGE_CHANGED,
};

#endif //LIVE_NOTIFICATOR_DEVICE_MESSAGE_TYPE_H